# iOS CircleCI 2.0 configuration file
#

version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Make IcedHTTP.framework for iOS
          command: make build-ios

      - run:
          name: Make IcedHTTP.framework for macOS
          command: make build-macos
